imports:
    - { resource: parameters.yml }
    - { resource: security.yml } 

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: false }
    templating:      { engines: ['twig'] }
    session:
        default_locale:  %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                dbname:   %database_name%
                user:     %database_user%
                host:     %database_host%
                password: %database_password%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default
        auto_mapping: true

# Swiftmailer Configuration
        #swiftmailer:
        #    transport: %mailer_transport%
        #    host:      %mailer_host%
        #    username:  %mailer_user%
        #    password:  %mailer_password%
        #    spool:     { type: memory }

jms_security_extra:
    secure_all_services: false