imports:
    - { resource: factory.php }
parameters:
    database_driver: pdo_pgsql
    database_host: %DB_HOST%
    database_port: %DB_PORT%
    database_name: %DB_NAME%
    database_user: %DB_USER%
    database_password: %DB_PASSWORD%
    mailer_transport: ~
    mailer_encryption: ~
    mailer_auth_mode: ~
    mailer_host: ~
    mailer_user: ~
    mailer_password: ~
    locale: ru
    secret: secret_code
    memcache_host: %CACHE_HOST%
    memcache_port: %CACHE_PORT%