parameters:
#    hello.example.class: Application\Ailove\HelloBundle\Example

services:
#    hello.example:
#        class: %hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
